[package]
name = "vuoto"
version = "0.0.1"
edition = "2024"

[dependencies]
base64 = "0.22.1"
env_home = "0.1.0"
inquire = "0.7.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
turbocache = "0.0.5"

[dev-dependencies]
tempfile = "3.20.0"

